language: java
sudo: required
matrix:
  include:
    - jdk: openjdk8
      env: JAVA_RELEASE=8 JAVA_VERSION=1.8 SCALA_VERSION=2.11
env:
  global:
    - NO_GCE_CHECK=true
script:
  - mvn -B verify -Djava.release=$JAVA_RELEASE -Djava.version=$JAVA_VERSION -Dscala.version=$SCALA_VERSION
cache:
  directories:
    - $HOME/.m2
after_success:
  - '{ mvn deploy --settings src/build/travis/settings.xml -DskipTests=true -B ; };'